version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/azure-carbon-exporter"
    schedule:
      interval: "weekly"
      time: "06:00"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
